#!/usr/bin/env python3
"""Plot relative energy errors generated by the md dimer example."""

from __future__ import annotations

import csv
import io
import os
import subprocess
from collections import defaultdict
from pathlib import Path


EXAMPLES_DIR = Path(__file__).resolve().parent
CRATE_DIR = EXAMPLES_DIR.parent
WEEK_DIR = CRATE_DIR.parent
MANIFEST = CRATE_DIR / "Cargo.toml"
OUTPUT = WEEK_DIR / "dimer.png"
os.environ.setdefault("MPLCONFIGDIR", str(CRATE_DIR / "target" / "matplotlib"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


def experiment_data() -> dict[str, tuple[np.ndarray, np.ndarray]]:
    """Run the Rust example and collect time and relative-error series."""
    cargo = Path("/opt/homebrew/bin/cargo")
    command = str(cargo) if cargo.exists() else "cargo"
    result = subprocess.run(
        [
            command,
            "run",
            "--quiet",
            "--manifest-path",
            str(MANIFEST),
            "--example",
            "dimer_energy",
        ],
        check=True,
        capture_output=True,
        text=True,
    )
    curves: dict[str, list[tuple[float, float]]] = defaultdict(list)
    for row in csv.DictReader(io.StringIO(result.stdout)):
        curves[row["method"]].append(
            (float(row["time"]), float(row["relative_energy_error"]))
        )
    return {name: np.asarray(values).T for name, values in curves.items()}


def main() -> None:
    curves = experiment_data()
    euler_time, euler_error = curves["Forward Euler (500)"]
    verlet_time, verlet_error = curves["Velocity-Verlet (500)"]
    long_time, long_error = curves["Velocity-Verlet (5000)"]
    scaled_long_error = 1000.0 * long_error

    figure, (short_axes, long_axes) = plt.subplots(
        1, 2, figsize=(12, 5), dpi=150, layout="constrained"
    )
    short_axes.plot(
        euler_time,
        euler_error,
        label="Forward Euler",
        color="firebrick",
        linewidth=2.0,
    )
    short_axes.plot(
        verlet_time,
        verlet_error,
        label="Velocity-Verlet",
        color="royalblue",
        linewidth=2.0,
    )
    short_axes.set(
        title="Both integrators: 500 steps",
        xlabel="time",
        ylabel=r"$(E(t)-E_0)/|E_0|$",
        xlim=(0.0, 5.0),
        ylim=(-0.1, 2.15),
    )
    short_axes.legend()

    long_axes.plot(
        long_time,
        scaled_long_error,
        color="royalblue",
        label="Velocity-Verlet",
        linewidth=1.5,
    )
    long_axes.set(
        title="Velocity-Verlet: 5000 steps",
        xlabel="time",
        ylabel=r"$10^3(E(t)-E_0)/|E_0|$",
        xlim=(0.0, 50.0),
        ylim=(-0.5, 0.5),
    )
    long_axes.set_xticks([0, 25, 50])
    long_axes.set_yticks([-0.5, -0.25, 0.0, 0.25, 0.5])

    figure.suptitle(
        r"Two-atom Lennard-Jones energy error ($r_0=1.2$, $\Delta t=0.01$)"
    )
    figure.savefig(OUTPUT)

    print(f"Euler final relative error: {euler_error[-1]:.9g}")
    print(f"Verlet 500-step maximum absolute relative error: {np.abs(verlet_error).max():.9g}")
    print(f"Verlet 5000-step maximum absolute relative error: {np.abs(long_error).max():.9g}")
    print(OUTPUT)


if __name__ == "__main__":
    main()
